### ISSUE TITLE
inspect command not working properly on new style CSV-W code lists

### ISSUE THREAD

**Issue by GDonRanasinghe** [GSS-Cogs/csvcubed#564]
It looks like the inspect command is erroring when handling parent-child hierarchies at the metadataprinter.py.

- [x] apply a suitable solution to fix the issue.
- [x] update any related unit and behave tests.
- [x] We need to be able to `inspect` both the older style code-lists using `notation` as the identifier as well as the newer style code lists wiith a separate uri identifier field. We need to test both of these.

Try and find a general solution to this that doesn't rely on checking whether a column with a specific name exists in the CSV-W -- we want to make sure we're not writing brittle code that will break whenever we change the CSV-W's format again.

The error is as below and the input examples are attached [https://app.zenhub.com/files/374709947/77ba7039-e027-453a-aec3-f083161625a8/download](https://app.zenhub.com/files/374709947/77ba7039-e027-453a-aec3-f083161625a8/download).

```
rob_barry@cloudshell:~$ csvcubed version
v0.1.6
rob_barry@cloudshell:~$ csvcubed inspect out/mixed-geographies-code-list.csv-metadata.json
2022-07-21 17:14:53,630 - csvcubed.cli.entrypoint - CRITICAL - Traceback (most recent call last):
  File "/home/rob_barry/.local/lib/python3.9/site-packages/csvcubed/cli/entrypoint.py", line 123, in inspect_command
    inspect(csvw_metadata_json_path)
  File "/home/rob_barry/.local/lib/python3.9/site-packages/csvcubed/cli/inspect/inspect.py", line 60, in inspect
    ) = _generate_printables(
  File "/home/rob_barry/.local/lib/python3.9/site-packages/csvcubed/cli/inspect/inspect.py", line 93, in _generate_printables
    metadata_printer = MetadataPrinter(
  File "<string>", line 6, in __init__
  File "/home/rob_barry/.local/lib/python3.9/site-packages/csvcubed/cli/inspect/metadataprinter.py", line 213, in __post_init__
    self.generate_codelist_results()
  File "/home/rob_barry/.local/lib/python3.9/site-packages/csvcubed/cli/inspect/metadataprinter.py", line 203, in generate_codelist_results
    self.result_concepts_hierachy_info = get_concepts_hierarchy_info(
  File "/home/rob_barry/.local/lib/python3.9/site-packages/csvcubed/cli/inspect/inspectdatasetmanager.py", line 214, in get_concepts_hierarchy_info
    concepts_tree = build_concepts_hierarchy_tree(
  File "/home/rob_barry/.local/lib/python3.9/site-packages/csvcubed/utils/skos/codelist.py", line 98, in build_concepts_hierarchy_tree
    tree.create_node(node_label, identifier=node_id, parent=node_parent_id)
  File "/home/rob_barry/.local/lib/python3.9/site-packages/treelib/tree.py", line 372, in create_node
    self.add_node(node, parent)
  File "/home/rob_barry/.local/lib/python3.9/site-packages/treelib/tree.py", line 307, in add_node
    raise NodeIDAbsentError("Parent node '%s' "
treelib.exceptions.NodeIDAbsentError: Parent node 'uk' is not in the tree
 (log.py:109)
```

**Comment by robons** [comment]
Here's a hacky patch I put together to make it work locally. Note that the hacky bit that won't be an appropriate long term solution is the following section:

```
+        notation_col_name = first(
+            columns, lambda c: c.column_title == "Uri Identifier"
+        ).column_title
```

the patch:

```
From b9d0244da662e77b3c7a1f5bf5acc6fd70559c9e Mon Sep 17 00:00:00 2001
From:A Person <a.person@example.com>
Date: Thu, 28 Jul 2022 11:48:00 +0100
Subject: [PATCH] stuff

---
 .../select_codelist_cols_by_dataset_url.sparql   |  3 +++
 src/csvcubed/cli/inspect/metadataprinter.py      | 16 +++++++++++-----
 src/csvcubed/models/inspectsparqlresults.py      |  4 ++--
 3 files changed, 16 insertions(+), 7 deletions(-)

diff --git a/src/csvcubed/cli/inspect/inspect_sparql_queries/select_codelist_cols_by_dataset_url.sparql b/src/csvcubed/cli/inspect/inspect_sparql_queries/select_codelist_cols_by_dataset_url.sparql
index 501fd981..7fe53bf4 100644
--- a/src/csvcubed/cli/inspect/inspect_sparql_queries/select_codelist_cols_by_dataset_url.sparql
+++ b/src/csvcubed/cli/inspect/inspect_sparql_queries/select_codelist_cols_by_dataset_url.sparql
@@ -10,7 +10,10 @@ WHERE {
     ?table csvw:url ?tableUrl.
     ?table csvw:tableSchema/csvw:column/rdf:rest*/rdf:first ?column.
 
+    OPTIONAL {
     ?column csvw:propertyUrl ?columnPropertyUrl.
+    }
+
     OPTIONAL{
         ?column csvw:valueUrl ?columnValueUrl.
     }
diff --git a/src/csvcubed/cli/inspect/metadataprinter.py b/src/csvcubed/cli/inspect/metadataprinter.py
index 83f2105c..7bc220f6 100644
--- a/src/csvcubed/cli/inspect/metadataprinter.py
+++ b/src/csvcubed/cli/inspect/metadataprinter.py
@@ -48,6 +48,7 @@ from csvcubed.models.inspectdataframeresults import (
 from csvcubed.utils.csvdataset import (
     transform_dataset_to_canonical_shape,
 )
+from csvcubed.utils.iterables import first
 from csvcubed.models.csvcubedexception import (
     InputNotSupportedException,
 )
@@ -114,16 +115,21 @@ class MetadataPrinter:
     def get_parent_label_notation_col_names(
         columns: List[CodelistColumnResult],
     ) -> Tuple[Optional[str], Optional[str], Optional[str]]:
-        parent_notation_col_name = get_codelist_col_title_by_property_url(
+        parent_uri_col_name = get_codelist_col_title_by_property_url(
             columns, CodelistPropertyUrl.SkosBroader
         )
         label_col_name = get_codelist_col_title_by_property_url(
             columns, CodelistPropertyUrl.RDFLabel
         )
-        notation_col_name = get_codelist_col_title_by_property_url(
-            columns, CodelistPropertyUrl.SkosNotation
-        )
-        return (parent_notation_col_name, label_col_name, notation_col_name)
+        print(columns)
+        notation_col_name = first(
+            columns, lambda c: c.column_title == "Uri Identifier"
+        ).column_title
+
+        #     get_codelist_col_title_by_property_url(
+        #     columns, CodelistPropertyUrl.SkosNotation
+        # )
+        return (parent_uri_col_name, label_col_name, notation_col_name)
 
     def generate_general_results(self):
         """
diff --git a/src/csvcubed/models/inspectsparqlresults.py b/src/csvcubed/models/inspectsparqlresults.py
index ea2b1556..04c612ed 100644
--- a/src/csvcubed/models/inspectsparqlresults.py
+++ b/src/csvcubed/models/inspectsparqlresults.py
@@ -206,7 +206,7 @@ class CodelistColumnResult(DataClassBase):
     Model to represent a codelist column.
     """
 
-    column_property_url: str
+    column_property_url: Optional[str]
     column_value_url: Optional[str]
     column_title: Optional[str]
 
@@ -462,7 +462,7 @@ def map_codelist_column_sparql_result(sparql_result: ResultRow) -> CodelistColum
     result_dict = sparql_result.asdict()
 
     result = CodelistColumnResult(
-        column_property_url=str(result_dict["columnPropertyUrl"]),
+        column_property_url=none_or_map(result_dict.get("columnPropertyUrl"), str),
         column_value_url=none_or_map(result_dict.get("columnValueUrl"), str),
         column_title=none_or_map(result_dict.get("columnTitle"), str),
     )
-- 
2.30.0
```

**Comment by GDonRanasinghe** [comment]
>Try and find a general solution to this that doesn't rely on checking whether a column with a specific name exists in the CSV-W -- we want to make sure we're not writing brittle code that will break whenever we change the CSV-W's format again.

The general solution I've found is to use the `primaryKey` from table json to identify the notation column of the code list. I am able to get the primary key through a sparql I've written (see https://github.com/GSS-Cogs/csvcubed/pull/580/files#diff-8095e017f3b605d559cfbaba810c8043c9f3a68ae93aceae96f7f6ff2f9c63bf).

But in the case of code list is using `uri_identifier` as the primary key, the RDF graph does not have this column - as it is suppressed. So even though I know the primary key, I am unable to use it as the col is suppressed. The work I've done to date on this is at: https://github.com/GSS-Cogs/csvcubed/pull/580/files.

Let's have a chat on this when you are back.
