### ISSUE TITLE
Serialisation of large datasets (>10000) fails

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#566]
When building large datasets with missing observations, the serialisation fails with a traceback despite having a `observation_status` column. No files are written and even with the `--validation-errors-to-file` flag results in no written files as the error is uncaptured.

```bash
2022-08-04 09:13:50,609 - csvcubed.cli.entrypoint - CRITICAL - Traceback (most recent call last):
  File "/Users/waf/.pyenv/versions/3.10.3/lib/python3.10/site-packages/csvcubed/cli/entrypoint.py", line 94, in build_command
    build(
  File "/Users/waf/.pyenv/versions/3.10.3/lib/python3.10/site-packages/csvcubed/cli/build.py", line 37, in build
    cube, json_schema_validation_errors, validation_errors = _extract_and_validate_cube(
  File "/Users/waf/.pyenv/versions/3.10.3/lib/python3.10/site-packages/csvcubed/cli/build.py", line 104, in _extract_and_validate_cube
    cube, json_schema_validation_errors, validation_errors = deserialiser(
  File "/Users/waf/.pyenv/versions/3.10.3/lib/python3.10/site-packages/csvcubed/readers/cubeconfig/v1/configdeserialiser.py", line 119, in get_cube_from_config_json
    code_list_schema_validation_errors = _configure_remaining_columns_by_convention(
  File "/Users/waf/.pyenv/versions/3.10.3/lib/python3.10/site-packages/csvcubed/readers/cubeconfig/v1/configdeserialiser.py", line 200, in _configure_remaining_columns_by_convention
    (qb_column, validation_errors) = map_column_to_qb_component(
  File "/Users/waf/.pyenv/versions/3.10.3/lib/python3.10/site-packages/csvcubed/readers/cubeconfig/v1/mapcolumntocomponent.py", line 36, in map_column_to_qb_component
    ) = schema_mapping.map_to_new_qb_dimension(
  File "/Users/waf/.pyenv/versions/3.10.3/lib/python3.10/site-packages/csvcubed/readers/cubeconfig/v1/columnschema.py", line 89, in map_to_new_qb_dimension
    new_dimension = NewQbDimension.from_data(
  File "/Users/waf/.pyenv/versions/3.10.3/lib/python3.10/site-packages/csvcubed/models/cube/qb/components/dimension.py", line 108, in from_data
    code_list=NewQbCodeList.from_data(CatalogMetadata(label), data, code_list_uri_style),
  File "/Users/waf/.pyenv/versions/3.10.3/lib/python3.10/site-packages/csvcubed/models/cube/qb/components/codelist.py", line 154, in from_data
    concepts = [NewQbConcept(c) for c in sorted(set(columnar_data))]
  File "/Users/waf/.pyenv/versions/3.10.3/lib/python3.10/site-packages/csvcubed/inputs.py", line 65, in pandas_input_to_columnar_str
    raise ValueError("Missing value found in data.")
ValueError: Missing value found in data.
 (log.py:109)
```

The bug was discovered using a NISRA data set stored at [https://github.com/GSS-Cogs/csvcubed-demo/tree/main/nisra_besesgsp](https://github.com/GSS-Cogs/csvcubed-demo/tree/main/nisra_besesgsp). 

Investigate and fix.

**Comment by canwaf** [comment]
Impact rated 4 - Very High, Probability rated 4 - Medium.

**Comment by canwaf** [comment]
I've pushed updates to the file to fix some more csv issues; however the bug remains.
```
/Users/waf/.pyenv/versions/3.10.3/lib/python3.10/site-packages/csvcubed/readers/cubeconfig/utils.py:42: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  data, data_errors = read_csv(csv_path)
2022-08-04 11:47:19,905 - csvcubed.cli.build - WARNING - Schema Validation Error: {'type': 'attribute', 'from_template': 'observation-status'} is not valid under any of the given schemas (build.py:92)
WARNING:csvcubed.cli.build:Schema Validation Error: {'type': 'attribute', 'from_template': 'observation-status'} is not valid under any of the given schemas
2022-08-04 11:47:19,906 - csvcubed.cli.entrypoint - CRITICAL - Traceback (most recent call last):
  File "/Users/waf/.pyenv/versions/3.10.3/lib/python3.10/site-packages/csvcubed/cli/entrypoint.py", line 94, in build_command
    build(
  File "/Users/waf/.pyenv/versions/3.10.3/lib/python3.10/site-packages/csvcubed/cli/build.py", line 59, in build
    with open(output_directory / validation_errors_file_out, "w+") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'out/out/validation-errors.json'
 (log.py:109)
CRITICAL:csvcubed.cli.entrypoint:Traceback (most recent call last):
  File "/Users/waf/.pyenv/versions/3.10.3/lib/python3.10/site-packages/csvcubed/cli/entrypoint.py", line 94, in build_command
    build(
  File "/Users/waf/.pyenv/versions/3.10.3/lib/python3.10/site-packages/csvcubed/cli/build.py", line 59, in build
    with open(output_directory / validation_errors_file_out, "w+") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'out/out/validation-errors.json'
```

**Comment by GDonRanasinghe** [comment]
I am able to get the output when not setting the `--validation-errors-to-file` flag. The issue around this tag seems to be something different and I've encountered this yesterday as well - see the bug ticket I created yesterday: https://app.zenhub.com/workspaces/features-squad-61b72275ac896c0010a1b00b/issues/gss-cogs/csvcubed/565.

When I run `csvcubed build BESESGSP.20220804T090834.csv -c qube-config.json`, I am getting the below output in console. Despite there is a warning from pandas, I can get the attached `out/` folder produced. Looks like the warning is related to low memory because of the size of the dataset.

[https://app.zenhub.com/files/374709947/18742364-9482-4d6b-b542-432cc5ed89df/download](https://app.zenhub.com/files/374709947/18742364-9482-4d6b-b542-432cc5ed89df/download)

```
/workspaces/csvcubed/src/csvcubed/readers/cubeconfig/utils.py:42: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  data, data_errors = read_csv(csv_path)

2022-08-04 14:43:48,359 - csvcubed.cli.build - WARNING - Schema Validation Error: {'type': 'attribute', 'from_template': 'observation-status'} is not valid under any of the given schemas (build.py:92)
WARNING:csvcubed.cli.build:Schema Validation Error: {'type': 'attribute', 'from_template': 'observation-status'} is not valid under any of the given schemas

Build Complete @ /workspaces/csvcubed/tests/test-cases/temp/out
```

**Comment by GDonRanasinghe** [comment]
Discussed with @canwaf and we have concluded the following:
1. There were a series of user errors when preparing the input csv and config file. Andrew addressed these issues by updating the input files.
2. The user will be using `csvcubed build` without `--validation-errors-to-file` tag as there is an issue with this tag - see the ticket at https://app.zenhub.com/workspaces/features-squad-61b72275ac896c0010a1b00b/issues/gss-cogs/csvcubed/565.

**Comment by GDonRanasinghe** [comment]
Reduced the estimate from 5 to 2 as only investigations and updating the inputs were required - no code changes.
