### ISSUE TITLE
out/out damned (validation errors)

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#570]
Fix this:
```bash
/Users/waf/.pyenv/versions/3.10.3/lib/python3.10/site-packages/csvcubed/readers/cubeconfig/utils.py:42: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  data, data_errors = read_csv(csv_path)
2022-08-04 11:47:19,905 - csvcubed.cli.build - WARNING - Schema Validation Error: {'type': 'attribute', 'from_template': 'observation-status'} is not valid under any of the given schemas (build.py:92)
WARNING:csvcubed.cli.build:Schema Validation Error: {'type': 'attribute', 'from_template': 'observation-status'} is not valid under any of the given schemas
2022-08-04 11:47:19,906 - csvcubed.cli.entrypoint - CRITICAL - Traceback (most recent call last):
  File "/Users/waf/.pyenv/versions/3.10.3/lib/python3.10/site-packages/csvcubed/cli/entrypoint.py", line 94, in build_command
    build(
  File "/Users/waf/.pyenv/versions/3.10.3/lib/python3.10/site-packages/csvcubed/cli/build.py", line 59, in build
    with open(output_directory / validation_errors_file_out, "w+") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'out/out/validation-errors.json'
 (log.py:109)
CRITICAL:csvcubed.cli.entrypoint:Traceback (most recent call last):
  File "/Users/waf/.pyenv/versions/3.10.3/lib/python3.10/site-packages/csvcubed/cli/entrypoint.py", line 94, in build_command
    build(
  File "/Users/waf/.pyenv/versions/3.10.3/lib/python3.10/site-packages/csvcubed/cli/build.py", line 59, in build
    with open(output_directory / validation_errors_file_out, "w+") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'out/out/validation-errors.json'
```

**Comment by robons** [comment]
Any update on this @canwaf ?

**Comment by canwaf** [comment]
No, @robons. I need to fiddle with my dev environment and boot up my ONS laptop. Next week.
