### ISSUE TITLE
BUG - Existing templates appear to be missing

### ISSUE THREAD

**Issue by CharlesRendle** [GSS-Cogs/csvcubed#838]
Brought to our attention by the DS Squad. Two members have been receiving an error when building CSV-Ws in which their config files use `from template : mixed-period` and `from template : gregorian-interval`.

Coincidentally, these two templates were the most recent additions (added ~03.2023). 

The autofill prompt in vscode recognises the templates as possible options when they are writing config files.

Neither @CharlesRendle or @nimshi89 have been able to replicate the issue on our development machines.

The error message obtained:
```
2023-06-20 13:52:06,191 - csvcubed.cli.entrypoint - CRITICAL - Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/csvcubed/cli/entrypoint.py", line 103, in build_command
    build_csvw(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/csvcubed/cli/buildcsvw/build.py", line 32, in build_csvw
    cube, json_schema_validation_errors, validation_errors = _extract_and_validate_cube(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/csvcubed/cli/buildcsvw/build.py", line 68, in _extract_and_validate_cube
    cube, json_schema_validation_errors, validation_errors = deserialiser(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/csvcubed/readers/cubeconfig/v1/configdeserialiser.py", line 101, in get_cube_from_config_json
    dtype = datatypes.get_pandas_datatypes(csv_path, config=config)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/csvcubed/readers/cubeconfig/v1/datatypes.py", line 109, in get_pandas_datatypes
    dtype = pandas_datatypes_from_columns_config(config["columns"])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/csvcubed/readers/cubeconfig/v1/datatypes.py", line 68, in pandas_datatypes_from_columns_config
    apply_preconfigured_values_from_template(column_config, column_label)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/csvcubed/readers/preconfiguredtemplates.py", line 91, in apply_preconfigured_values_from_template
    template_file = _get_template_file_from_template_lookup(template_value)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/csvcubed/readers/preconfiguredtemplates.py", line 43, in _get_template_file_from_template_lookup
    raise Exception(f"Couldn't find template your looking for '{template_value}'.")
Exception: Couldn't find template your looking for 'gregorian-interval'.
 (log.py:95)
```

And with debug statements:
```
2023-06-20 14:44:51,467 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): purl.org:443 (connectionpool.py:1003)
2023-06-20 14:44:52,554 - urllib3.connectionpool - DEBUG - https://purl.org:443 "GET /csv-cubed/resources/units.json HTTP/1.1" 302 244 (connectionpool.py:456)
2023-06-20 14:44:52,558 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): raw.githubusercontent.com:443 (connectionpool.py:1003)
2023-06-20 14:44:52,836 - urllib3.connectionpool - DEBUG - https://raw.githubusercontent.com:443 "GET /GSS-Cogs/reusable-rdf-resources/main/units.json HTTP/1.1" 200 8991 (connectionpool.py:456)
2023-06-20 14:44:52,845 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): purl.org:80 (connectionpool.py:228)
2023-06-20 14:44:53,172 - urllib3.connectionpool - DEBUG - http://purl.org:80 "GET /csv-cubed/resources/measures.json HTTP/1.1" 301 0 (connectionpool.py:456)
2023-06-20 14:44:53,174 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): purl.org:443 (connectionpool.py:1003)
2023-06-20 14:44:54,071 - urllib3.connectionpool - DEBUG - https://purl.org:443 "GET /csv-cubed/resources/measures.json HTTP/1.1" 302 247 (connectionpool.py:456)
2023-06-20 14:44:54,074 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): raw.githubusercontent.com:443 (connectionpool.py:1003)
2023-06-20 14:44:54,344 - urllib3.connectionpool - DEBUG - https://raw.githubusercontent.com:443 "GET /GSS-Cogs/reusable-rdf-resources/main/measures.json HTTP/1.1" 200 428 (connectionpool.py:456)
2023-06-20 14:44:54,351 - requests_cache.policy.actions - DEBUG - Cache directives from request headers: {} (actions.py:85)
2023-06-20 14:44:54,352 - csvcubed.readers.preconfiguredtemplates - DEBUG - The template lookup/index file: https://purl.org/csv-cubed/qube-config/templates/preset_column_config.json (preconfiguredtemplates.py:27)
```

While attempting to diagnose this issue, I found the unit test which tests we are able to produce this error in `test_preset_column_templates.py`

```
def test_exception_is_raised_when_given_wrong_template_file_path():
    column_config = {"from_template": "this_doesn't_exist"}
    with pytest.raises(Exception) as excinfo:
        apply_preconfigured_values_from_template(column_config)
        assert "Couldn't find template your looking for." in str(excinfo)
```
Using the `from_template` value `this_doesn't_exist` we expect the test to fail as in the function [_get_template_file_from_template_lookup(template_value)](https://github.com/GSS-Cogs/csvcubed/blob/main/src/csvcubed/readers/preconfiguredtemplates.py#L41) the template value `this_doesn't_exist` will not be able to match at value in `preset_column_config.json`.
However, when changing the the template value in the test to one which should exist such as `column_config = {"from_template": "mixed-period"}` the test will still pass as if this template value is also responsible for producing an error.

**Comment by CharlesRendle** [comment]
Impact - Moderate (3)
Probability - Odd one because we have been unable to replicate the issue. In one repository of data sets, 19/43 are using either of the problematic templates which means < 50% of data sets being affected (in that particular repository) - Moderate (3)

Combined Score - 9 (Important Bug)

**Comment by CharlesRendle** [comment]
[Clearing user and system cache](https://www.tomsguide.com/how-to/how-to-clear-the-cache-on-mac) on the haunted machines seems to fix this issue. 

We should add the guide (linked above) on how to clear user and system cache to our documentation as a possible known solution to this error.
