### ISSUE TITLE
[BUG] Cannot use 'Value' as the column name for observation column

### ISSUE THREAD

**Issue by GregoryJPavier** [GSS-Cogs/csvcubed#856]
**Describe the issue:**
If a dataset uses the word 'Value' as a title for the observation column it will build, but when inspecting the output it will result in an error.

If you were to commit and push changes made to a dataset or its json file (where 'Value' is used as above), e.g. total-value-of-uk-exports under the Family-ESS repo, then the github build action will also fail, resulting in the same error in the logs.

**Reproducible steps / Code example:**
Find any dataset with 'Value' as the title for the observation column, build it using its config json file, then inspect the output.

OR

Push changes made to such a dataset or its json file to trigger a build.
The output of a failed build can be seen here: https://github.com/GSS-Cogs/family-ess/actions/runs/5599506508/jobs/10240554713

**Error message obtained / Resulting behaviour:**
`2023-07-20 17:48:14,961 - csvcubed.cli.inspectcsvw.inspect - DEBUG - Metadata json-ld path: /Users/gregorypavier/family-ess/out/total-value-of-uk-exports.csv-metadata.json (inspect.py:33)
2023-07-20 17:48:15,512 - csvcubed.inspect.tableschema - INFO - Successfully parsed csvw json-ld to rdf graph. (tableschema.py:145)
2023-07-20 17:48:15,512 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - Root path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed (sparqlquerymanager.py:101)
2023-07-20 17:48:15,512 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - select_csvw_table_schema_file_dependencies query file path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/inspect/sparql_handler/sparql_queries/select_csvw_table_schema_file_dependencies.sparql (sparqlquerymanager.py:110)
2023-07-20 17:48:15,656 - csvcubed.inspect.tableschema - DEBUG - Loading dependent file containing table schema year.table.json into RDF graph. (tableschema.py:73)
2023-07-20 17:48:15,657 - csvcubed.utils.json - DEBUG - Loading JSON from file /Users/gregorypavier/family-ess/out/year.table.json (json.py:58)
2023-07-20 17:48:16,202 - csvcubed.inspect.tableschema - DEBUG - Loading dependent file containing table schema ons-geography-code-list-for-total-value-of-uk-exports.table.json into RDF graph. (tableschema.py:73)
2023-07-20 17:48:16,202 - csvcubed.utils.json - DEBUG - Loading JSON from file /Users/gregorypavier/family-ess/out/ons-geography-code-list-for-total-value-of-uk-exports.table.json (json.py:58)
2023-07-20 17:48:16,709 - csvcubed.inspect.tableschema - INFO - Successfully loaded 2 table schemas into the rdf graph. (tableschema.py:95)
2023-07-20 17:48:16,709 - csvcubed.inspect.tableschema - DEBUG - Loading RDF dependencies (tableschema.py:171)
2023-07-20 17:48:16,709 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - Root path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed (sparqlquerymanager.py:101)
2023-07-20 17:48:16,709 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - select_metadata_dependencies query file path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/inspect/sparql_handler/sparql_queries/select_metadata_dependencies.sparql (sparqlquerymanager.py:110)
2023-07-20 17:48:16,715 - csvcubed.inspect.tableschema - DEBUG - Treating relative dependency 'year.csv-metadata.json' as absolute URL 'file:///Users/gregorypavier/family-ess/out/year.csv-metadata.json'. (tableschema.py:204)
2023-07-20 17:48:16,715 - csvcubed.inspect.tableschema - DEBUG - Loading dataset dependency 'file:///Users/gregorypavier/family-ess/out/year.csv-metadata.json' covering uriSpace 'year.csv#' in dataset 'total-value-of-uk-exports.csv#dependency/year' (tableschema.py:219)
2023-07-20 17:48:16,715 - csvcubed.inspect.tableschema - DEBUG - Anticipated RDF format: 'json-ld'. (tableschema.py:227)
2023-07-20 17:48:17,220 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - Root path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed (sparqlquerymanager.py:101)
2023-07-20 17:48:17,220 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - select_metadata_dependencies query file path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/inspect/sparql_handler/sparql_queries/select_metadata_dependencies.sparql (sparqlquerymanager.py:110)
2023-07-20 17:48:17,226 - csvcubed.inspect.tableschema - DEBUG - Treating relative dependency 'ons-geography-code-list-for-total-value-of-uk-exports.csv-metadata.json' as absolute URL 'file:///Users/gregorypavier/family-ess/out/ons-geography-code-list-for-total-value-of-uk-exports.csv-metadata.json'. (tableschema.py:204)
2023-07-20 17:48:17,226 - csvcubed.inspect.tableschema - DEBUG - Loading dataset dependency 'file:///Users/gregorypavier/family-ess/out/ons-geography-code-list-for-total-value-of-uk-exports.csv-metadata.json' covering uriSpace 'ons-geography-code-list-for-total-value-of-uk-exports.csv#' in dataset 'total-value-of-uk-exports.csv#dependency/ons-geography-code-list-for-total-value-of-uk-exports' (tableschema.py:219)
2023-07-20 17:48:17,227 - csvcubed.inspect.tableschema - DEBUG - Anticipated RDF format: 'json-ld'. (tableschema.py:227)
2023-07-20 17:48:17,738 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - Root path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed (sparqlquerymanager.py:101)
2023-07-20 17:48:17,738 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - select_metadata_dependencies query file path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/inspect/sparql_handler/sparql_queries/select_metadata_dependencies.sparql (sparqlquerymanager.py:110)
2023-07-20 17:48:17,744 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - Root path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed (sparqlquerymanager.py:101)
2023-07-20 17:48:17,744 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - ask_is_codelist query file path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/inspect/sparql_handler/sparql_queries/ask_is_codelist.sparql (sparqlquerymanager.py:110)
2023-07-20 17:48:17,748 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - Root path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed (sparqlquerymanager.py:101)
2023-07-20 17:48:17,749 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - ask_is_qb_dataset query file path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/inspect/sparql_handler/sparql_queries/ask_is_qb_dataset.sparql (sparqlquerymanager.py:110)
2023-07-20 17:48:17,753 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - Root path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed (sparqlquerymanager.py:101)
2023-07-20 17:48:17,753 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - ask_is_codelist query file path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/inspect/sparql_handler/sparql_queries/ask_is_codelist.sparql (sparqlquerymanager.py:110)
2023-07-20 17:48:17,757 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - Root path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed (sparqlquerymanager.py:101)
2023-07-20 17:48:17,757 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - ask_is_qb_dataset query file path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/inspect/sparql_handler/sparql_queries/ask_is_qb_dataset.sparql (sparqlquerymanager.py:110)
2023-07-20 17:48:17,761 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - Root path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed (sparqlquerymanager.py:101)
2023-07-20 17:48:17,762 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - select_catalog_metadata query file path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/inspect/sparql_handler/sparql_queries/select_catalog_metadata.sparql (sparqlquerymanager.py:110)
2023-07-20 17:48:17,825 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - Root path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed (sparqlquerymanager.py:101)
2023-07-20 17:48:17,825 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - select_data_set_dsd_csv_url query file path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/inspect/sparql_handler/sparql_queries/select_data_set_dsd_csv_url.sparql (sparqlquerymanager.py:110)
2023-07-20 17:48:17,877 - csvcubed.inspect.inspectdatasetmanager - DEBUG - Dataset path: /Users/gregorypavier/family-ess/out/total-value-of-uk-exports.csv (inspectdatasetmanager.py:41)
2023-07-20 17:48:17,884 - csvcubed.inspect.inspectdatasetmanager - INFO - Successfully loaded csv into dataframe. (inspectdatasetmanager.py:46)
2023-07-20 17:48:17,884 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - Root path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed (sparqlquerymanager.py:101)
2023-07-20 17:48:17,884 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - select_is_pivoted_shape_data_set query file path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/inspect/sparql_handler/sparql_queries/select_is_pivoted_shape_data_set.sparql (sparqlquerymanager.py:110)
2023-07-20 17:48:17,924 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - Root path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed (sparqlquerymanager.py:101)
2023-07-20 17:48:17,924 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - select_column_definitions query file path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/inspect/sparql_handler/sparql_queries/select_column_definitions.sparql (sparqlquerymanager.py:110)
2023-07-20 17:48:18,079 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - Root path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed (sparqlquerymanager.py:101)
2023-07-20 17:48:18,079 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - select_dsd_qube_components query file path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/inspect/sparql_handler/sparql_queries/select_dsd_qube_components.sparql (sparqlquerymanager.py:110)
2023-07-20 17:48:18,111 - csvcubed.models.inspect.sparqlresults - DEBUG - result_dict: {'dsdUri': rdflib.term.URIRef('total-value-of-uk-exports.csv#structure'), 'component': rdflib.term.URIRef('total-value-of-uk-exports.csv#component/statistical-geography'), 'componentProperty': rdflib.term.URIRef('total-value-of-uk-exports.csv#dimension/statistical-geography'), 'componentPropertyLabel': rdflib.term.Literal('Statistical Geography', lang='en'), 'componentOrder': rdflib.term.Literal('1', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#integer')), 'componentPropertyType': rdflib.term.URIRef('http://purl.org/linked-data/cube#DimensionProperty'), 'required': rdflib.term.Literal('true', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#boolean'))} (sparqlresults.py:285)
2023-07-20 17:48:18,111 - csvcubed.models.inspect.sparqlresults - DEBUG - result_dict: {'dsdUri': rdflib.term.URIRef('total-value-of-uk-exports.csv#structure'), 'component': rdflib.term.URIRef('total-value-of-uk-exports.csv#component/year'), 'componentProperty': rdflib.term.URIRef('total-value-of-uk-exports.csv#dimension/year'), 'componentPropertyLabel': rdflib.term.Literal('Year', lang='en'), 'componentOrder': rdflib.term.Literal('2', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#integer')), 'componentPropertyType': rdflib.term.URIRef('http://purl.org/linked-data/cube#DimensionProperty'), 'required': rdflib.term.Literal('true', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#boolean'))} (sparqlresults.py:285)
2023-07-20 17:48:18,112 - csvcubed.models.inspect.sparqlresults - DEBUG - result_dict: {'dsdUri': rdflib.term.URIRef('total-value-of-uk-exports.csv#structure'), 'component': rdflib.term.URIRef('total-value-of-uk-exports.csv#component/measure-type'), 'componentProperty': rdflib.term.URIRef('http://purl.org/linked-data/cube#measureType'), 'componentOrder': rdflib.term.Literal('3', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#integer')), 'componentPropertyType': rdflib.term.URIRef('http://purl.org/linked-data/cube#DimensionProperty'), 'required': rdflib.term.Literal('true', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#boolean'))} (sparqlresults.py:285)
2023-07-20 17:48:18,112 - csvcubed.models.inspect.sparqlresults - DEBUG - result_dict: {'dsdUri': rdflib.term.URIRef('total-value-of-uk-exports.csv#structure'), 'component': rdflib.term.URIRef('total-value-of-uk-exports.csv#component/unit'), 'componentProperty': rdflib.term.URIRef('http://purl.org/linked-data/sdmx/2009/attribute#unitMeasure'), 'componentOrder': rdflib.term.Literal('4', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#integer')), 'componentPropertyType': rdflib.term.URIRef('http://purl.org/linked-data/cube#AttributeProperty'), 'required': rdflib.term.Literal('true', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#boolean'))} (sparqlresults.py:285)
2023-07-20 17:48:18,112 - csvcubed.models.inspect.sparqlresults - DEBUG - result_dict: {'dsdUri': rdflib.term.URIRef('total-value-of-uk-exports.csv#structure'), 'component': rdflib.term.URIRef('total-value-of-uk-exports.csv#component/total-value-of-uk-exports'), 'componentProperty': rdflib.term.URIRef('total-value-of-uk-exports.csv#measure/total-value-of-uk-exports'), 'componentPropertyLabel': rdflib.term.Literal('Total value of UK exports', lang='en'), 'componentOrder': rdflib.term.Literal('5', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#integer')), 'componentPropertyType': rdflib.term.URIRef('http://purl.org/linked-data/cube#MeasureProperty'), 'required': rdflib.term.Literal('true', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#boolean'))} (sparqlresults.py:285)
2023-07-20 17:48:18,112 - csvcubed.models.inspect.sparqlresults - DEBUG - result_dict: {'dsdUri': rdflib.term.URIRef('total-value-of-uk-exports.csv#structure'), 'component': rdflib.term.URIRef('total-value-of-uk-exports.csv#component/lower-confidence-interval'), 'componentProperty': rdflib.term.URIRef('total-value-of-uk-exports.csv#attribute/lower-confidence-interval'), 'componentPropertyLabel': rdflib.term.Literal('Lower Confidence Interval', lang='en'), 'componentOrder': rdflib.term.Literal('6', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#integer')), 'componentPropertyType': rdflib.term.URIRef('http://purl.org/linked-data/cube#AttributeProperty'), 'required': rdflib.term.Literal('false', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#boolean'))} (sparqlresults.py:285)
2023-07-20 17:48:18,113 - csvcubed.models.inspect.sparqlresults - DEBUG - result_dict: {'dsdUri': rdflib.term.URIRef('total-value-of-uk-exports.csv#structure'), 'component': rdflib.term.URIRef('total-value-of-uk-exports.csv#component/upper-confidence-interval'), 'componentProperty': rdflib.term.URIRef('total-value-of-uk-exports.csv#attribute/upper-confidence-interval'), 'componentPropertyLabel': rdflib.term.Literal('Upper Confidence Interval', lang='en'), 'componentOrder': rdflib.term.Literal('7', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#integer')), 'componentPropertyType': rdflib.term.URIRef('http://purl.org/linked-data/cube#AttributeProperty'), 'required': rdflib.term.Literal('false', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#boolean'))} (sparqlresults.py:285)
2023-07-20 17:48:18,113 - csvcubed.models.inspect.sparqlresults - DEBUG - result_dict: {'dsdUri': rdflib.term.URIRef('total-value-of-uk-exports.csv#structure'), 'component': rdflib.term.URIRef('total-value-of-uk-exports.csv#component/observation-status'), 'componentProperty': rdflib.term.URIRef('total-value-of-uk-exports.csv#attribute/observation-status'), 'componentPropertyLabel': rdflib.term.Literal('Observation Status', lang='en'), 'componentOrder': rdflib.term.Literal('8', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#integer')), 'componentPropertyType': rdflib.term.URIRef('http://purl.org/linked-data/cube#AttributeProperty'), 'required': rdflib.term.Literal('false', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#boolean'))} (sparqlresults.py:285)
2023-07-20 17:48:18,113 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - Root path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed (sparqlquerymanager.py:101)
2023-07-20 17:48:18,113 - csvcubed.inspect.sparql_handler.sparqlquerymanager - DEBUG - select_codelists_and_cols query file path: /Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/inspect/sparql_handler/sparql_queries/select_codelists_and_cols.sparql (sparqlquerymanager.py:110)
2023-07-20 17:48:18,154 - csvcubed.cli.entrypoint - CRITICAL - Traceback (most recent call last):
  File "/Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/cli/entrypoint.py", line 127, in inspect_command
    inspect(csvw_metadata_json_path)
  File "/Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/cli/inspectcsvw/inspect.py", line 54, in inspect
    ) = _generate_printables(
  File "/Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/cli/inspectcsvw/inspect.py", line 86, in _generate_printables
    metadata_printer = MetadataPrinter(data_cube_repository)
  File "<string>", line 4, in __init__
  File "/Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/cli/inspectcsvw/metadataprinter.py", line 83, in __post_init__
    self.get_datacube_results()
  File "/Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/cli/inspectcsvw/metadataprinter.py", line 185, in get_datacube_results
    ) = transform_dataset_to_canonical_shape(
  File "/Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/utils/csvdataset.py", line 421, in transform_dataset_to_canonical_shape
    return _melt_pivoted_shape(
  File "/Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/utils/csvdataset.py", line 379, in _melt_pivoted_shape
    melted_df = _melt_data_set(canonical_shape_dataset, measure_components)
  File "/Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/csvcubed/utils/csvdataset.py", line 310, in _melt_data_set
    return pd.melt(
  File "/Users/gregorypavier/.pyenv/versions/3.10.10/lib/python3.10/site-packages/pandas/core/reshape/melt.py", line 56, in melt
    raise ValueError(
ValueError: value_name (Value) cannot match an element in the DataFrame columns.
 (log.py:95)`

**Expected behaviour:**
Inspect command should run with no errors / git build action should not fail

**Additional Information:**
NA

**Version information + Operating System:**
csvcubed version - 0.4.6
OS - macOS Ventura 13.4.1 (c)

**Comment by CharlesRendle** [comment]
Looks similar to the issue that arose when [upgrading to pandas 2.0](https://app.zenhub.com/workspaces/features-squad-61b72275ac896c0010a1b00b/issues/gh/gss-cogs/csvcubed/809). I think we discovered that the test case in this instance was mislabelled which didn't address the root problem for the original test case.

Triage:
Impact - 3.5: Existing workaround is to rename the `value` column but we shouldn't do this and from memory I'm not sure if this introduces another issue (also in the `melt()` function).

Probability - 3 (Moderate)

Result - 10.5 = Critical Bug
